export default {
	SET_ACTIVE_SLIDE: 'SET_ACTIVE_SLIDE',
	AUTH_USER: 'AUTH_USER',
	LOG_IN: 'LOG_IN',
	LOG_OUT: 'LOG_OUT',
	SET_YOUTUBE_STATE: 'SET_YOUTUBE_STATE',
	SET_IS_MOBILE: 'SET_IS_MOBILE',
	SET_IS_SLIDING: 'SET_IS_SLIDING',
}